name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository == 'cachesdev/panekit'
    permissions:
      contents: write # create releases
      pull-requests: write # create PRs
      id-token: write # provenance

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for changelog generation

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      # I have no tests :(
      # Optional: Run tests
      # - name: Run tests
      #   run: npm test

      # publish calls prepack which compiles our package
      - name: Create Release PR or Publish
        uses: changesets/action@v1
        with:
          version: npm run changeset:version
          publish: npm run changeset:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
